### ISSUE TITLE
Bottom banner hiding info

### ISSUE THREAD

**Issue by cgutierr-zgz** [quicktype/quicktype#1757] opened 2021-07-15 08:36 UTC
The **bottom banner** on the page **hides important info**, it'd be great if you could give the user the option to either close/hide it or just to be below the page itself so it doesn't hide the text,

Here's what I mean:
![Image Quicktype](https://i.gyazo.com/0f5114c6a12c37a174feb28bfa7a4c94.png)

**Comment by Sun3** [comment] 2021-07-17 21:03
Same issue here and I had opened a ticket at [Issue 1752](https://github.com/quicktype/quicktype/issues/1752)

**Comment by NatoBoram** [comment] 2021-07-23 17:32
Duplicate of #1657

**Closed** 2023-01-03 18:16 UTC
