### ISSUE TITLE
The whole code is not visible due to the bar below

### ISSUE THREAD

**Issue by yhackup** [quicktype/quicktype#1879] opened 2022-02-08 07:51 UTC
The whole code is not visible due to the bar below

![image](https://user-images.githubusercontent.com/15657038/152941787-6ef59fa1-504d-4319-a00a-4799d128fbb9.png)

**Comment by NatoBoram** [comment] 2022-02-14 16:31
Duplicate of #1657

**Closed** 2023-01-04 15:30 UTC
