### ISSUE TITLE
Scrollable view in quicktype website

### ISSUE THREAD

**Issue by amitdvs** [quicktype/quicktype#1873] opened 2022-01-27 10:13 UTC
![image](https://user-images.githubusercontent.com/85055524/151338318-a4d34a73-eb46-4acd-8ea1-ef8424bb0f05.png)

Please update UI scrollable. your baner for hiring overlap result part

**Comment by NatoBoram** [comment] 2022-03-11 19:36
Duplicate of https://github.com/quicktype/quicktype/issues/1657

**Closed** 2023-01-03 18:44 UTC
