### ISSUE TITLE
Please add null safe wrapper support in dart language

### ISSUE THREAD

**Issue by Scienticious** [quicktype/quicktype#1843] opened 2021-12-01 11:35 UTC

**Comment by 3SCadmin** [comment] 2021-12-04 15:35
1st: Really amazing tool, respect for your work.

But yes, please update the code for the DART language.

DART output  cut&paste from your website will show errors in vscode and will not run:
`The parameter 'name' can't have a value of 'null' because of its type, but the implicit default value is 'null'.
Try adding either an explicit non-'null' default value or the 'required' modifier.dartmissing_default_value_for_parameter`

My quick-fix was prefixing each argument of the constructor with 'required' , I'm sure there are better ways to do this.

**Comment by NatoBoram** [comment] 2022-01-05 18:54
Duplicate of #1673

**Closed** 2023-01-04 15:32 UTC
