### ISSUE TITLE
Unable to Scroll down on JSON container

### ISSUE THREAD

**Issue by tingaz-2nye** [quicktype/quicktype#1797] opened 2021-09-22 11:22 UTC
I am unable to scroll down and view the rest of the code because of the banner which is fixed at the bottom of screen plus the json container is not scrollable

**Comment by jeffctown** [comment] 2021-09-22 12:16
It's also really hard to copy anything at the bottom.  Please make your ad dismissible.

**Comment by grant** [comment] 2021-09-28 17:55
Yes, this makes app.quicktype.io a lot harder to use. Something changed in the working UI

**Comment by NatoBoram** [comment] 2021-11-25 17:12
Duplicate of #1657

**Closed** 2023-01-03 18:16 UTC

**Comment by lsh-0** [comment] 2023-05-11 01:18
Not a duplicate, I can't scroll down on the output json container at https://app.quicktype.io
