### ISSUE TITLE
Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by vjpr** [quicktype/quicktype#1890] opened 2022-02-22 13:28 UTC
```
Error: Cannot find module 'lodash'
Require stack:
- /xxx.pnpm/quicktype-core@6.0.70/node_modules/quicktype-core/dist/language/Dart.js
```

This happens when using pnpm. `lodash` should be explicit dep - not rely on hoisting - which I assume is issue.

**Comment by dvdsgl** [comment] 2023-01-04 15:31
Duplicate of #1870

**Closed** 2023-01-04 15:31 UTC
