### ISSUE TITLE
OC The conversion effect is not consistent with the expectation.

### ISSUE THREAD

**Issue by px123zx** [quicktype/quicktype#1061] opened 2018-09-11 03:38 UTC
I have a json like that .
`{
		"applyUrl": "",
		"id": ""
}`
Results obtained
```
@property (nonatomic, copy) NSString *applyURL;
@property (nonatomic, copy) NSString *identifier;
```
but i want results 
```
@property (nonatomic, copy) NSString *applyUrl;
@property (nonatomic, copy) NSString *id;
```
How can I get that result?

**Comment by schani** [comment] 2018-09-11 04:41
Currently this is not possible - we're using the target language's naming conventions.  There is an open issue to preserve the JSON's property names as-is.  Please consider contributing!

Duplicate of #1021

**Closed by schani** 2018-09-11 04:41 UTC

**Comment by dvdsgl** [comment] 2018-09-11 04:42
We also intentionally alias `id` as `identifier` based on feedback from another Objective-C user who claimed this would be an undesirable property name 🤷‍♂️
