### ISSUE TITLE
Banner blocking bottom part of app

### ISSUE THREAD

**Issue by astronaako** [quicktype/quicktype#1696] opened 2021-04-08 04:50 UTC
![image](https://user-images.githubusercontent.com/18577543/113970145-c16e4600-984f-11eb-8108-8cca02944a7e.png)
This banner seems to be blocking the UI below it

**Comment by imedboumalek** [comment] 2021-04-13 12:40
Yes. It's annoying.

**Comment by NatoBoram** [comment] 2021-07-23 17:30
Duplicate of #1657

**Closed** 2021-11-25 05:19 UTC
