### ISSUE TITLE
not support null safety in dart language

### ISSUE THREAD

**Issue by MohammedSalehelShazly** [quicktype/quicktype#1993] opened 2022-09-19 13:06 UTC
please make the model support null safety..
just add the **required** keyword
and make the constructor constant with the **const** keyword.

**Comment by Miamoto-Musashi** [comment] 2022-11-11 22:26
model creation is not null safe  when all optional setting is active, given a json like:

```json
   "commoditiesSummary": {
        "totElements": 2,
        "createdAt": "2022-09-08T09: 58: 32.743000000Z",
        "updatedAt": "2022-09-08T09: 58: 32.743000000Z"
    },
```

it produce a model like 

```dart
class CommoditiesSummary {
  CommoditiesSummary({
    this.totElements,
    this.createdAt,
    this.updatedAt,
  });

  int totElements;
  String createdAt;
  String updatedAt;
```
instead  of the null safe version (with question point)
```dart
class CommoditiesSummary {
  CommoditiesSummary({
    this.totElements,
    this.createdAt,
    this.updatedAt,
  });

  int? totElements;
  String? createdAt;
  String? updatedAt;
```

**Comment by NatoBoram** [comment] 2022-11-14 16:53
Duplicate of #1673 and #1755

**Closed** 2023-01-06 15:56 UTC
