### ISSUE TITLE
dart codegen needs to be updated for null safety

### ISSUE THREAD

**Issue by unicomp21** [quicktype/quicktype#1794] opened 2021-09-15 12:26 UTC

**Comment by imSaharukh** [comment] 2021-09-25 19:02
yes need that

**Comment by json1994** [comment] 2021-09-27 01:53
+1

**Comment by chetanxpatil** [comment] 2021-09-30 13:47
+1

**Comment by CrossBread** [comment] 2021-11-01 18:25
Duplicate of #1673

**Closed** 2023-01-03 22:39 UTC
