### ISSUE TITLE
Flutter Null Safety

### ISSUE THREAD

**Issue by ganger1003** [quicktype/quicktype#1924] opened 2022-04-09 07:07 UTC
I have noticed that your repository is awesome and very helpful to others. As you know Flutter has published with null safety. But this repository does not support this feature. Can you please develop this feature so that we can use this more preciously. Thank you for your effort.

**Comment by 877209649** [comment] 2022-04-09 14:34
+1

**Comment by f1dz** [comment] 2022-04-13 05:12
I would love it if ```null-safety``` supported. I have been using this tool every day

**Comment by f1dz** [comment] 2022-04-13 05:14
Duplicate of #1673

**Closed** 2023-01-04 15:29 UTC
