### ISSUE TITLE
Placing to_json / from_json methods in nlohmann namespace leads to multiply compile errors

### ISSUE THREAD

**Issue by llilakoblock** [quicktype/quicktype#1494] opened 2020-06-07 09:52 UTC
Take a look at this issue in nlohmann's repo: https://github.com/nlohmann/json/issues/780

**Comment by Jusonex** [comment] 2020-07-07 12:13
This is a duplicate of #1185. Unfortunately, this problem makes the codegen unusable with MSVC.

Have you considered integrating the solution suggested in https://github.com/quicktype/quicktype/issues/1185#issuecomment-506614282? It seems to fix the problem for me.

**Closed** 2023-01-10 01:17 UTC
