### ISSUE TITLE
The hiring announcement covers part of the JSON with no way to dismiss 

### ISSUE THREAD

**Issue by aspiforgreat** [quicktype/quicktype#1864] opened 2022-01-14 18:47 UTC
I wish you best of luck with your hiring efforts. Its a great site. Could you please give us a way of hiding the banner so I can see the bottom of my JSON?

**Comment by NatoBoram** [comment] 2022-02-02 20:20
Duplicate of #1657

**Closed** 2023-01-03 18:16 UTC
