### ISSUE TITLE
JSON to Dart Model Translation Error

### ISSUE THREAD

**Issue by SemihGursoy** [quicktype/quicktype#2036] opened 2022-12-15 22:44 UTC
When you try to translate a JSON to Dart Model with the 'Make all properties required' option selected, it adds '@' symbol at the start of the 'required' keyword when in fact it should be 'required' not '@required'.

Example JSON:

`[
    {
        "id": "9310",
        "order_id": "3110",
        "product_id": "19",
        "variant_id": "72",
        "name": "Pizza Tonno - Klein (24 cm)",
        "image": "pizza/Pizza Thunfisch.png",
        "quantity": "4",
        "price": "4.5",
        "stripe_price_id": null,
        "total": "18",
        "sub_products": null,
        "extras": null,
        "note": null,
        "extra_selection": null
    },
    {
        "id": "9526",
        "order_id": "3110",
        "product_id": "19",
        "variant_id": "72",
        "name": "Pizza Tonno - Klein (24 cm)22",
        "image": "pizza/Pizza Thunfisch.png",
        "quantity": "4",
        "price": "4.5",
        "stripe_price_id": null,
        "total": "18",
        "sub_products": null,
        "extras": null,
        "note": null,
        "extra_selection": null
    }
]`

**Comment by clragon** [comment] 2023-01-03 18:10
Duplicate of #1673

**Closed** 2023-01-04 15:09 UTC
