### ISSUE TITLE
Please add support for null safety in dart language.

### ISSUE THREAD

**Issue by bittuRichestsoft** [quicktype/quicktype#1855] opened 2021-12-23 05:38 UTC
Please add support for null safety in dart language.

**Comment by Phuong9Pay** [comment] 2021-12-24 03:41
Same.

**Comment by vthakkar66** [comment] 2021-12-24 07:49
Yes, Please add support for null safety :)

**Comment by chunlee-thong** [comment] 2022-01-03 10:13
https://github.com/chunlee-thong/dart-quicktype
Give this a try if it fits your use case

**Comment by NatoBoram** [comment] 2022-01-05 18:54
Duplicate of #1673

**Comment by RmondJone** [comment] 2022-03-11 16:54
可以看看我提交的PR,现在等待官方合并，[#1904](https://github.com/quicktype/quicktype/pull/1904)
You can take a look at the PR I submitted, now waiting for the official merge。[#1904](https://github.com/quicktype/quicktype/pull/1904)

**Closed** 2023-01-04 15:31 UTC
