### ISSUE TITLE
oneOf is not supported/validated properly

### ISSUE THREAD

**Issue by Ark-kun** [quicktype/quicktype#1103] opened 2018-10-31 06:35 UTC
AFAIK, `oneOf` means exactly one type from the list. quicktype, however, allows constructing objects that have any mix of properties.

```
{
    "oneOf": [
        {
            "type": "object",
            "properties": {
                "a_1": {"type": "string"},
                "a_2": {"type": "string"}
            }
        },
        {
            "type": "object",
            "properties": {
                "b_1": {"type": "string"},
                "b_2": {"type": "string"}
            }
        },
        {
            "type": "object",
            "properties": {
                "c_1": {"type": "string"},
                "c_2": {"type": "string"}
            }
        }
    ]
}
```

This schema should only allow properties of one type to be set at once, but generated code never enforces that and can construct invalid objects.

**Comment by schani** [comment] 2018-10-31 13:56
Yes.  Supporting `oneOf` (or `anyOf`, for that matter) according to spec, vs just as a flattened version of all the constituent types requires a lot more logic in the deserialization.  We already have a framework in place (transformers - only implemented in C# and Python yet) to incorporate the logic, but a lot of work still needs to be done.  See #493.  I can explain more if you're interested.

**Comment by schani** [comment] 2018-10-31 13:57
Duplicate of #493

**Closed by schani** 2018-10-31 13:57 UTC
