### ISSUE TITLE
Dart Null Safety Compatibility Issue.

### ISSUE THREAD

**Issue by athulnanda123** [quicktype/quicktype#1830] opened 2021-11-21 05:14 UTC
classes generated using app.quicktype.io is not supporting Dart Null Safety, please fix it.

**Comment by NatoBoram** [comment] 2021-11-25 17:08
Duplicate of #1673

**Comment by RmondJone** [comment] 2022-03-11 16:55
可以看看我提交的PR,现在等待官方合并，[#1904](https://github.com/quicktype/quicktype/pull/1904)
You can take a look at the PR I submitted, now waiting for the official merge。[#1904](https://github.com/quicktype/quicktype/pull/1904)

**Closed** 2023-01-03 18:16 UTC
