### ISSUE TITLE
Type names lose first character in figma-types TypeScript input scenario

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#778] opened 2018-04-09 23:00 UTC
In Figma types, `type BlendMode = ...` in [TypeScript](https://github.com/quicktype/figma-types/blob/22b8e8fc52a90c4a960a4166e8630fce5ef752af/types/types.ts#L52) becomes `enum LendMode` in [output](https://github.com/quicktype/figma-types/blob/22b8e8fc52a90c4a960a4166e8630fce5ef752af/swift/Figma.swift#L152).

See commit `22b8e8fc52a90c4a960a4166e8630fce5ef752af`

**Comment by schani** [comment] 2018-04-10 00:55
Duplicate of #407

**Closed by schani** 2018-04-10 00:55 UTC
