### ISSUE TITLE
bottom card covers the last part of code

### ISSUE THREAD

**Issue by kcibdev** [quicktype/quicktype#1882] opened 2022-02-11 08:32 UTC
![cv](https://user-images.githubusercontent.com/32621169/153559693-3d8016e6-650f-403c-865c-1b2e6484e00e.PNG)
This card above covers the last part of the code and I can't scroll to the bottom since it is covered

**Comment by NatoBoram** [comment] 2022-02-14 16:31
Duplicate of #1657

**Closed** 2023-01-03 18:43 UTC
