### ISSUE TITLE
Dart compatible with freezed package.

### ISSUE THREAD

**Issue by agelogeo** [quicktype/quicktype#2034] opened 2022-12-15 14:15 UTC
Hello, 

The freezed package feature for Dart/Flutter would be absolutely awesome if it was working perfectly. Currently it doesn't support null safety, so the option make all fields optional doesn't change anything on the code. Also make or fields required on freezed package it only accepts required , not @required before each field.

**Comment by clragon** [comment] 2023-01-03 18:10
Duplicate of #1673

**Closed** 2023-01-04 15:10 UTC
