### ISSUE TITLE
how to make all properties required when create a dart model use quicktype-core from nodejs

### ISSUE THREAD

**Issue by 826327700** [quicktype/quicktype#2014] opened 2022-11-11 02:10 UTC
I copy the example code and run , output:
```
import 'dart:convert';

Person personFromJson(String str) => Person.fromJson(json.decode(str));

String personToJson(Person data) => json.encode(data.toJson());

class Person {
    Person({
        this.name,
        this.age,
    });

    String name;
    int age;

    factory Person.fromJson(Map<String, dynamic> json) => Person(
        name: json["name"],
        age: json["age"],
    );

    Map<String, dynamic> toJson() => {
        "name": name,
        "age": age,
    };
}
```

I want to know more options, such as "make all properties required" ,"make all properties final".I can't find the related document description

**Comment by NatoBoram** [comment] 2022-11-14 16:54
Duplicate of https://github.com/quicktype/quicktype/issues/1755

**Closed** 2023-01-04 15:11 UTC
