### ISSUE TITLE
Cannot see all generated code

### ISSUE THREAD

**Issue by starteNCS** [quicktype/quicktype#1903] opened 2022-03-11 14:34 UTC
When generating larger files the bottom banner hides the last few lines of generated code.

I would suggest to either add an option to close the banner, or add it below the page, not on top of it.

![image](https://user-images.githubusercontent.com/30404993/157887589-b272f121-8ff5-4ae9-9137-18a6d8201f8d.png)

**Comment by NatoBoram** [comment] 2022-03-11 19:37
Duplicate of https://github.com/quicktype/quicktype/issues/1657

**Closed** 2023-01-03 18:16 UTC
