### ISSUE TITLE
Multiple JSON Delete/+sample buttons not functional

### ISSUE THREAD

**Issue by goleary** [quicktype/quicktype#1700] opened 2021-04-13 22:37 UTC
I'm using [quicktype](https://app.quicktype.io/) from a Windows 10 machine with chrome LTS.

I'm attempting to use the Multiple JSON source, but the delete & the +sample buttons aren't working.

I see this error being thrown in the console:

```
react-dom.production.min.js:101 Uncaught RangeError: Maximum call stack size exceeded
    at l.get (index.tsx:342)
    at l.get (index.tsx:342)
    at l.get (index.tsx:342)
    at l.get (index.tsx:342)
    at l.get (index.tsx:342)
    at l.get (index.tsx:342)
    at l.get (index.tsx:342)
    at l.get (index.tsx:342)
    at l.get (index.tsx:342)
    at l.get (index.tsx:342)
```

Repro steps
- go [here](https://app.quicktype.io/)
- select "Source Type" of "Multiple JSON"
- click the trash icon
- nothing happens (Error thrown)

**Comment by vaaski** [comment] 2021-04-16 17:28
this is a known issue, has been reported multiple times, and is almost 2 months old.
i've already tried to help in #1665 but no response so far.

i run into this issue every time i try to use quicktype, and i'd love to get this fixed. @schani @dvdsgl

**Comment by dvdsgl** [comment] 2021-04-16 17:40
Duplicate of #1665

**Closed by dvdsgl** 2021-04-16 17:40 UTC
