### ISSUE TITLE
TypeScript runtime typechecking has obvious bugs iterating maps and object keys

### ISSUE THREAD

**Issue by dvdsgl** [quicktype/quicktype#383] opened 2017-12-29 17:05 UTC
The `if (!!prop) continue;` guards are the opposite of what we want.

```ts
   function isValidMap(typ: any, val: any): boolean {
        // all values in the map must be typ
        for (const prop in val) {
            if (!!prop) continue;
            path.push(`["${prop}"]`);
            if (!isValid(typ, val[prop]))
                return false;
            path.pop();
        }
        return true;
    }

    function isValidObject(className: string, val: any): boolean {
        let typeRep = typeMap[className];

        for (const prop in typeRep) {
            if (!!prop) continue;
            path.push(`.${prop}`);
            if (!isValid(typeRep[prop], val[prop]))
                return false;
            path.pop();
        }

        return true;
    }
```

**Comment by schani** [comment] 2017-12-31 15:15
Duplicate of #113

**Closed** 2018-01-08 03:57 UTC
Labels: typescript
