### ISSUE TITLE
Use of serde instead of serde_json

### ISSUE THREAD

**Issue by AntonBlomstrom** [quicktype/quicktype#1493] opened 2020-06-06 18:16 UTC
https://github.com/quicktype/quicktype/blob/7a6a0fbdaa817ac36d0acf8701fe92e36ae261d6/src/quicktype-core/language/Rust.ts#L378
Think this line might be outdated. I changed it to `use serde::{Deserialize, Serialize};` in my own code.

**Comment by mocsy** [comment] 2020-06-10 11:12
Duplicate of #1210 

It might as well be optional, as current code compiles with edition  2018 disabled as well.

**Closed** 2020-06-11 15:19 UTC
