### ISSUE TITLE
Footer Problem

### ISSUE THREAD

**Issue by Anas-jed** [quicktype/quicktype#1688] opened 2021-03-26 06:40 UTC
the footer which says **we are hiring engineers for a new exciting....** hides all the answer that is at the end... i am removing it through inspect element but that is not the solution, you should either post it somewhere else or display properly....

<img width="1280" alt="Screen Shot 2021-03-26 at 11 39 13 AM" src="https://user-images.githubusercontent.com/43311899/112592560-fded7b00-8e27-11eb-8d52-0fd5ce7c650f.png">

**Comment by NatoBoram** [comment] 2022-01-05 18:58
Duplicate of #1657

**Closed** 2023-01-03 18:16 UTC
