### ISSUE TITLE
Update Dart Syntax

### ISSUE THREAD

**Issue by ashitests** [quicktype/quicktype#2003] opened 2022-10-17 12:06 UTC
![new format for required tags](https://user-images.githubusercontent.com/60913636/196172793-1bef0fe7-1192-494d-8157-0fec9156cc14.PNG)

Please update creation of Models using new required tag syntax that comes without a '@' symbol.

**Comment by clragon** [comment] 2022-10-28 16:01
Duplicate of #1673

**Comment by NatoBoram** [comment] 2022-11-14 16:53
Duplicate of https://github.com/quicktype/quicktype/issues/1755

**Closed** 2023-01-03 18:06 UTC
