### ISSUE TITLE
Cannot see bottom code

### ISSUE THREAD

**Issue by hatsadin09** [quicktype/quicktype#1809] opened 2021-10-14 04:01 UTC
Hiring popup block bottom code : (
![image](https://user-images.githubusercontent.com/21187872/137249324-4ddb8e06-d546-4206-84f3-64f223c0e772.png)

**Comment by NatoBoram** [comment] 2022-01-05 18:58
Duplicate of #1657

**Closed** 2023-01-03 22:39 UTC
