### ISSUE TITLE
option to not order my properties alhabetically 

### ISSUE THREAD

**Issue by blackholeearth** [quicktype/quicktype#233] opened 2017-10-20 11:41 UTC
i dont wanna lost my  order of properties . cus i bind it to table . this mess up order. i need to reorder it again . pelase  let user to choose  if he want sort property alhabvetically or not.

**Comment by dvdsgl** [comment] 2017-10-20 14:40
Thanks for your feedback, we plan to fix this!

Duplicate of #40

**Closed by dvdsgl** 2017-10-20 14:40 UTC
