### ISSUE TITLE
Ad at bottom covering essential areas

### ISSUE THREAD

**Issue by ryanoff** [quicktype/quicktype#1779] opened 2021-08-13 04:47 UTC
Currently there is an ad at the bottom of the site about hiring engineers. It's a great ad, but it covers some essential items at the bottom of the page. For example, if my input JSON is quite long, there is no way to see the final line since this ad covers it. I have needed to inspect the HTML on this page and hide this element so I can edit the final line of my input JSON.

**Comment by SimonBishop** [comment] 2021-09-12 23:46
I ended up using uBlock for the Chrome browser to see the bottom of the screen.  Very annoying!

**Comment by rimedar** [comment] 2021-11-17 16:26
You can please remove the banner in the footer, or put a button to close it, since there is information that remains under the banner and cannot be seen. Thanks.  
![image](https://user-images.githubusercontent.com/11951317/142239851-3a93f391-9145-491e-9ddc-6e3cf8a64f3d.png)

**Comment by NatoBoram** [comment] 2021-11-25 17:12
Duplicate of #1657

**Closed** 2023-01-03 18:16 UTC
