### ISSUE TITLE
Add an option for using @SerializedName

### ISSUE THREAD

**Issue by ndawg** [quicktype/quicktype#938] opened 2018-07-02 19:30 UTC
In some Java and Kotlin code, field names do not have their case converted. For example, consider this input into the converter:
```
{
   "dummy_type": "hello"
}
```

The generated code is the following (in Kotlin):
```
data class Dummy (
    val dummyType: String? = null
)
```

Using GSON for this does not work. The field `dummy_type` is not recognized as being equivalent to `dummyType`. I propose an option be added to use the [`@SerializedName`](https://google.github.io/gson/apidocs/com/google/gson/annotations/SerializedName.html) annotation present in GSON. So, the resulting code would be:
```
data class Dummy (
    @SerializedName("dummy_type")
    val dummyType: String? = null
)
```

**Comment by schani** [comment] 2018-07-02 19:32
Duplicate of #897

**Closed by schani** 2018-07-02 19:32 UTC
