### ISSUE TITLE
Dart NullSafety

### ISSUE THREAD

**Issue by H-Zaman** [quicktype/quicktype#1792] opened 2021-09-07 15:17 UTC
Please add dart nullsafety :) please

**Comment by j-j-gajjar** [comment] 2021-09-24 12:47
+1

**Comment by json1994** [comment] 2021-09-27 01:54
+1

**Comment by rquttaineh** [comment] 2021-10-06 10:26
+1

**Comment by shofizone** [comment] 2021-11-02 13:41
Please add null safety for Dart

**Comment by fy5220** [comment] 2021-11-17 10:29
+1

**Comment by NatoBoram** [comment] 2021-11-25 17:01
Duplicate of #1673

**Closed** 2023-01-04 15:33 UTC
