### ISSUE TITLE
Fix Naming Style Transformation

### ISSUE THREAD

**Issue by mattbudish** [quicktype/quicktype#317] opened 2017-12-05 18:01 UTC
For C++ it converts names with single-letter parts from camel case to snake case in a way inconsistent with the convention. For example, "theATeam" becomes "the_aTeam", where more commonly (as in Lodash) it would be transformed to "the_a_team".

**Comment by schani** [comment] 2017-12-05 18:27
Duplicate of #191

**Closed by schani** 2017-12-05 18:27 UTC
